version: '2'
services:
  eoncamera-couchbase:
    build:
      context: .
      dockerfile: couchbase/Couchbase.Dockerfile
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      - BUCKET=eoncamera
    # volumes:
    #     - ~/volumes/jhipster/eoncamera/couchbase/:/opt/couchbase/var
